# Generated by Django 3.0 on 2024-07-01 10:01

from django.db import migrations


def transfer_data(apps, schema_editor):
    OldProfile = apps.get_model('oc_lettings_site', 'Profile')
    NewProfile = apps.get_model('profiles', 'Profile')
    User = apps.get_model('auth', 'User')

    # Transfer Profile data
    for old_profile in OldProfile.objects.all():
        user = User.objects.get(pk=old_profile.user.pk)
        new_profile = NewProfile(
            user=user,
            favorite_city=old_profile.favorite_city
        )
        new_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
