# Generated by Django 3.0 on 2024-07-01 10:01

from django.db import migrations


def transfer_data(apps, schema_editor):
    OldAddress = apps.get_model('oc_lettings_site', 'Address')
    OldLetting = apps.get_model('oc_lettings_site', 'Letting')
    NewAddress = apps.get_model('lettings', 'Address')
    NewLetting = apps.get_model('lettings', 'Letting')

    for old_address in OldAddress.objects.all():
        new_address = NewAddress(
            number=old_address.number,
            street=old_address.street,
            city=old_address.city,
            state=old_address.state,
            zip_code=old_address.zip_code,
            country_iso_code=old_address.country_iso_code
        )
        new_address.save()

    for old_letting in OldLetting.objects.all():
        new_letting = NewLetting(
            title=old_letting.title,
            address=old_letting.address
        )
        new_letting.save()
  

class Migration(migrations.Migration):

    dependencies = [
        ('lettings', '0001_initial'),
        ('oc_lettings_site', '0001_initial'),  
    ]

    operations = [
        migrations.RunPython(transfer_data),
    ]
